nullifier = "0x009edeebc281630eb2babc51a267925032536b977efc51c04e4138839cef4ac7"
root = "0x122d78ca456c8e553b43e424fc31a00ffb418cace65975d359eb5036761f33d8"
new_commitment = "0x063620193f895d8ffb4d76da9fbd6261d3055e903159c5689907e2309bda79fa"
timeout = "0x0000000000000000000000000000000000000000000000000000000000000000"
pk_stealth = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_swap = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_R = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_meta = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_enc = "0x0000000000000000000000000000000000000000000000000000000000000000"
sk_lo = "0x00000000000000000000000000000000000000000000000000000000deadbeef"
sk_hi = "0x0000000000000000000000000000000000000000000000000000000000000000"
in_chain_id = "0x0000000000000000000000000000000000000000000000000000000000000001"
in_value = 1000
in_asset_id = "0x0000000000000000000000000000000000000000000000000000000000001234"
in_owner = "0x2bd7cb96eefe5020c9f992d53248589a062d68510755729a9c220dfce6785e84"
in_fallback_owner = "0x0000000000000000000000000000000000000000000000000000000000000000"
in_timeout = "0x0000000000000000000000000000000000000000000000000000000000000000"
in_salt = "0x000000000000000000000000000000000000000000000000000000000000aaaa"
proof_length = 1
path_elements = ["0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"]
path_indices = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
out_chain_id = "0x0000000000000000000000000000000000000000000000000000000000000001"
out_value = 1000
out_asset_id = "0x0000000000000000000000000000000000000000000000000000000000001234"
out_owner = "0x000000000000000000000000000000000000000000000000000000000000cafe"
out_fallback_owner = "0x0000000000000000000000000000000000000000000000000000000000000000"
out_timeout = "0x0000000000000000000000000000000000000000000000000000000000000000"
out_salt = "0x000000000000000000000000000000000000000000000000000000000000bbbb"
swap_id = "0x0000000000000000000000000000000000000000000000000000000000000000"
r_lo = "0x0000000000000000000000000000000000000000000000000000000000000000"
r_hi = "0x0000000000000000000000000000000000000000000000000000000000000000"
pk_meta_x = "0x0000000000000000000000000000000000000000000000000000000000000000"
pk_meta_y = "0x0000000000000000000000000000000000000000000000000000000000000000"
encrypted_salt = "0x0000000000000000000000000000000000000000000000000000000000000000"
