encrypted_salt = ""
h_R = ""
h_enc = ""
h_meta = ""
h_swap = ""
in_asset_id = ""
in_chain_id = ""
in_fallback_owner = ""
in_owner = ""
in_salt = ""
in_timeout = ""
in_value = ""
new_commitment = ""
nullifier = ""
out_asset_id = ""
out_chain_id = ""
out_fallback_owner = ""
out_owner = ""
out_salt = ""
out_timeout = ""
out_value = ""
path_elements = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
path_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
pk_meta_x = ""
pk_meta_y = ""
pk_stealth = ""
proof_length = ""
r_hi = ""
r_lo = ""
root = ""
sk_hi = ""
sk_lo = ""
swap_id = ""
timeout = ""
