nullifier = "0x0fde3cc31634ffe9aaaef808d88b4bb259163a324e1868f9516eb522722b625d"
root = "0x2968c5feea9c109eefe5115b41b0ea2591aaef3b198a54057146a412b0e11466"
new_commitment = "0x02e97862a15223795e702abde03a650a2a1124ca80043aa6f3582cb5cc7c7842"
timeout = "0x00000000000000000000000000000000000000000000000000000000699e0c9a"
pk_stealth = "0x037fa43ae0cadc8cbf5748bd48f61133014a9d42d2ce803b4f5f0accf88f14a2"
h_swap = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_R = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_meta = "0x0000000000000000000000000000000000000000000000000000000000000000"
h_enc = "0x0000000000000000000000000000000000000000000000000000000000000000"
sk_lo = "0x00000000000000000000000000000000e0050b6f6f590299759a1e1de68327f0"
sk_hi = "0x0000000000000000000000000000000027cb77fe352f4a42faa576b15f09bfee"
in_chain_id = "0x0000000000000000000000000000000000000000000000000000000000007a69"
in_value = 1000
in_asset_id = "0x0101010101010101010101010101010101010101010101010101010101010101"
in_owner = "0x037fa43ae0cadc8cbf5748bd48f61133014a9d42d2ce803b4f5f0accf88f14a2"
in_fallback_owner = "0x23a01bd8dde9f43571956bdd153442ec16d9dbe28d999668bae510803926af63"
in_timeout = "0x00000000000000000000000000000000000000000000000000000000699e0c9a"
in_salt = "0x09921f9082e4204260abe472e5d82cf0bda4af259f17191757fd9c77a180e8ce"
proof_length = 1
path_elements = ["0x076fd33f943adf32401b47358cf5b0a2e9a0714e2b2b502ad818c4ee19d09669", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"]
path_indices = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
out_chain_id = "0x0000000000000000000000000000000000000000000000000000000000007a69"
out_value = 1000
out_asset_id = "0x0101010101010101010101010101010101010101010101010101010101010101"
out_owner = "0x0469a28bd7f0acd914ad3a81dbcc19624c6e73d74c82a09adc561baf91e1c49e"
out_fallback_owner = "0x0000000000000000000000000000000000000000000000000000000000000000"
out_timeout = "0x0000000000000000000000000000000000000000000000000000000000000000"
out_salt = "0x1ca07e79a14d063e1669c931862e1bcdd2b6cf0aafad1d45644a226692d770b6"
swap_id = "0x0000000000000000000000000000000000000000000000000000000000000000"
r_lo = "0x0000000000000000000000000000000000000000000000000000000000000000"
r_hi = "0x0000000000000000000000000000000000000000000000000000000000000000"
pk_meta_x = "0x0000000000000000000000000000000000000000000000000000000000000000"
pk_meta_y = "0x0000000000000000000000000000000000000000000000000000000000000000"
encrypted_salt = "0x0000000000000000000000000000000000000000000000000000000000000000"
