[package]
name = "tee_swap"
version = "0.1.0"
authors = ["Meyanis95 <yanis.meziane@essec.edu>"]
edition = "2024"

[lib]
path = "src/lib/lib.rs"

[dependencies]
light-poseidon = "0.4.0"
alloy-primitives = "1"
ark-bn254 = "0.5"
ark-ff = "0.5"
rand = "0.8"
zk-kit-lean-imt = "0.1"
