[31337]
endpoint_url = "http://localhost:8545"

[31337.bool]
use_mock_verifier = true

[31337.address]
verifier_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
private_utxo_address = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
tee_lock_address = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
