# Public inputs (witnesses to be proven on-chain)
root = "0x5bff49d71b7ee294fcf1f9694d811c1b2228cccc52d01e8deeb3eebc459f0c4"
nullifiers = ["0xf4853301a6e130e81948bf0b9e3f3f1522cdf9ee388278857444904700cb153", "0x21d0b3d5278b9339f65968bde078108fdc71c82a864b1d1d0908a8378f355151"]
commitments_out = ["0x1b2a41e40670db69490b7db2e79850284159edfa946a8e4ebd9109787c4e1f47", "0x8421fccbfb32c22899ac2d7ed5db508d6b3a99134c2313eff9a0fa8c9dd3116"]

# Input notes (private)
input_values = [100000000, 0]
input_salts = ["0x94485c80fa244c27", "0x0"]
input_owner = "0x14690c253b7392ec967c8d43d0c84fd6e2f3349c99ef96fb716e638034a2ea1"
input_asset_id = 1
input_maturity_date = 1893456000

# Merkle proof paths for each input note
path_indices = [[0, 0, 0], [1, 0, 0]]
path_elements = [["0x565c12316ad10e143a81706cc73490177a1154df881475c8b8f0257a8c1d707", "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864", "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1"], ["0x1b581e24c1c9b2e04edd33bf1cf87dc2626a40cf3089b8cb8636db30f5610b89", "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864", "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1"]]

# Output notes (private)
output_values = [1000000, 99000000]
output_salts = ["0x229d76a291abdd01", "0x399fe7dbd0da2fdb"]
output_owners = ["0x9224288ae909c4f3dd9f174dba6919f7109b44baf09fd95a6e463d386a6e98f", "0x14690c253b7392ec967c8d43d0c84fd6e2f3349c99ef96fb716e638034a2ea1"]
output_asset_ids = [1, 1]
output_maturity_date = 1893456000

# Private key
private_key = "0x8f03e2d5802e0308"
