[31337]
endpoint_url = "http://localhost:8545"

[31337.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[31337.address]
shielded_pool_address = "0x04C89607413713Ec9775E14b954286519d836FEf"
composite_verifier_address = "0xdbC43Ba45381e02825b14322cDdd15eC4B3164E6"
attestation_registry_address = "0x1fA02b2d6A771842690194Cf62D91bdd92BfE28d"
mock_token_address = "0x4C4a2f8c81640e47606d3fd77B353E87Ba015584"
deposit_verifier_address = "0x162A433068F51e18b7d13932F27e66a3f99E6890"
transfer_verifier_address = "0x922D6956C99E12DFeB3224DEA977D0939758A1Fe"
withdraw_verifier_address = "0x5081a39b8A5f0E35a8D959395a630b68B74Dd30f"

[11155111]
endpoint_url = "${SEPOLIA_RPC_URL}"

[11155111.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[11155111.address]
deposit_verifier_address = "${DEPOSIT_VERIFIER_ADDRESS}"
transfer_verifier_address = "${TRANSFER_VERIFIER_ADDRESS}"
withdraw_verifier_address = "${WITHDRAW_VERIFIER_ADDRESS}"
attestation_registry_address = "${ATTESTATION_REGISTRY_ADDRESS}"
