[31337]
endpoint_url = "http://localhost:8545"

[31337.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[31337.address]
shielded_pool_address = "0x1291Be112d480055DaFd8a610b7d1e203891C274"
composite_verifier_address = "0x4c5859f0F772848b2D91F1D83E2Fe57935348029"
attestation_registry_address = "0x809d550fca64d94Bd9F66E60752A544199cfAC3D"
mock_token_address = "0x5f3f1dBD7B74C6B46e8c44f98792A1dAf8d69154"
deposit_verifier_address = "0x9d4454B023096f34B160D6B654540c56A1F81688"
transfer_verifier_address = "0x5eb3Bc0a489C5A8288765d2336659EbCA68FCd00"
withdraw_verifier_address = "0x36C02dA8a0983159322a80FFE9F24b1acfF8B570"

[11155111]
endpoint_url = "${SEPOLIA_RPC_URL}"

[11155111.bool]
use_mock_verifier = "${USE_MOCK_VERIFIER}"

[11155111.address]
deposit_verifier_address = "${DEPOSIT_VERIFIER_ADDRESS}"
transfer_verifier_address = "${TRANSFER_VERIFIER_ADDRESS}"
withdraw_verifier_address = "${WITHDRAW_VERIFIER_ADDRESS}"
attestation_registry_address = "${ATTESTATION_REGISTRY_ADDRESS}"
