[package]
name = "stablecoin"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr/", tag="v3.0.0-devnet.6-patch.1", directory="aztec" }
balance_set = { git="https://github.com/AztecProtocol/aztec-nr/", tag="v3.0.0-devnet.6-patch.1", directory="balance-set" }
